### ISSUE TITLE
NCEI Timeseries Orthogonal 1.1 check 

### ISSUE THREAD

**Issue by mbiddle-bcodmo** [ioos/compliance-checker-web#43]
When I try to run the [compliance checker web](https://data.ioos.us/compliance/index.html) for NCEI Timeseries Orthogonal 1.1, the report states:

> ncei-timeseries-orthogonal:latest check

However, when I run NCEI Timeseries Orthogonal 2.0, the report states:

>ncei-timeseries-orthogonal:2.0 check

**Comment by benjwadams** [comment]
@mbiddle-bcodmo, this was fixed by a commit on compliance checker https://github.com/ioos/compliance-checker/commit/c970f98518f50ad16f296111b3990561aaeec450 and should also now be fixed in compliance-checker-web now that the compliance checker version has been updated.  I ran the checks in question and did not encounter the ":latest" issue with 1.1 ortho TS check.  Both checks showed their respective versions instead of ":latest".  As I'm no longer able to reproduce this faulty behavior, I'm going to mark this as closed.  If you decide to test the new checker for yourself, please make sure you clear browser cache.
